version: '3.8'

services:

  # The Database
  db:
    image: mysql:8.0          
    container_name: movie_db
    environment:
      MYSQL_ROOT_PASSWORD: secret123   
      MYSQL_DATABASE: movies_db       
    ports:
      - "3306:3306"           
    volumes:
      - mysql_data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  # The Flask Backend 
  backend:
    build: ./backend          
    container_name: movie_backend
    ports:
      - "5000:5000"           
    depends_on:
      db:
        condition: service_healthy   
    env_file:
      - ./backend/.env        

# Persistent Volume 
volumes:
  mysql_data:                 